{
 "title": "Daedalus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Parallelism",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_metrics_alive_stream_threads) by (job)"
    }
   ]
  },
  {
   "title": "Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate{namespace=\"daedalus\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kafka_streams_stream_task_metrics_process_total{namespace=\"daedalus\",task_id=~\"0_.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{namespace=\"daedalus\", task_name=\"Source:_KafkaSource\"}) by (job)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(avg_over_time(java_lang_operatingsystem_processcpuload{job=\"daedalus/kafka-streams-metrics\"}[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{namespace=\"daedalus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{topic=\"word-events\"}>0) by (job)"
    }
   ]
  },
  {
   "title": "Kafka Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kafka_streams_stream_task_metrics_process_total{namespace=\"daedalus\",task_id=~\"0_.*\"}[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "min(java_lang_Runtime_Uptime)" }
   ]
  },
  {
   "title": "Kafka Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg(kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{task_id=~\"1_.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "End-to-end Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_eventTimeLag{namespace=\"daedalus\", quantile=\"0.95\"}) by (job)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}